// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#define DEBUG
#define REAL_ROBOT
//#define USE_COUNTER

#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "CANTalon.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "PigeonImu.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> intakeintakeRollerController;
	static std::shared_ptr<SpeedController> climberclimberMotorController;
	static std::shared_ptr<Ultrasonic> gearPickupultrasonic1;
	static std::shared_ptr<Ultrasonic> gearPickupultrasonic2;
	static std::shared_ptr<Servo> gearPickupleftGateServo;
	static std::shared_ptr<Servo> gearPickuprightGateServo;
	static std::shared_ptr<Servo> gearPickupleftPushServo;
	static std::shared_ptr<Servo> gearPickuprightPushServo;
	static std::shared_ptr<CANTalon> drivetrainfrontRightTurnMotor;
	static std::shared_ptr<CANTalon> drivetrainfrontRightMoveMotor;
	static std::shared_ptr<AnalogInput> drivetrainfrontRightEncoder;
	static std::shared_ptr<CANTalon> drivetrainfrontLeftTurnMotor;
	static std::shared_ptr<CANTalon> drivetrainfrontLeftMoveMotor;
	static std::shared_ptr<AnalogInput> drivetrainfrontLeftEncoder;
	static std::shared_ptr<CANTalon> drivetrainbackRightTurnMotor;
	static std::shared_ptr<CANTalon> drivetrainbackRightMoveMotor;
	static std::shared_ptr<AnalogInput> drivetrainbackRightEncoder;
	static std::shared_ptr<CANTalon> drivetrainbackLeftTurnMotor;
	static std::shared_ptr<CANTalon> drivetrainbackLeftMoveMotor;
	static std::shared_ptr<AnalogInput> drivetrainbackLeftEncoder;
	static std::shared_ptr<SpeedController> dumpsterdumpMotor;
	static std::shared_ptr<Servo> dumpsterdumpServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static std::shared_ptr<PowerDistributionPanel> pdb;
	static std::shared_ptr<Ultrasonic> drivetrainUltrasonic1;
	static std::shared_ptr<Ultrasonic> drivetrainUltrasonic2;
//	static std::shared_ptr<Servo> cameraServo;
	static std::shared_ptr<PigeonImu> pidgey;

	static std::shared_ptr<DigitalInput> climberclimberLimitSwtich;

	static std::shared_ptr<Encoder> drivetrainDistEncoder;

	static std::shared_ptr<Counter> gearPickupPushEncoder;
	static std::shared_ptr<DigitalInput> gearPickupPushEncLimit;
	static std::shared_ptr<Spark> gearPickupPushMotor;

	static std::shared_ptr<CANTalon> shooterUpperShooterMotor;
	static std::shared_ptr<Spark> shooterLowerShooterMotor;

	static void init();
};
#endif
