// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShoverPosition.h"
#include "AutoGearMiddle.h"
#include "DriveForward.h"
#include "TurnToAngle.h"
#include "ParallelToWallWithGyro.h"
#include "openGate.h"
#include "pushGear.h"
#include "DriveSideways.h"
#include "TurnWheels.h"
#include "closeGate.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoGearMiddle::AutoGearMiddle() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	AddSequential(new TurnWheels(0, 0.5));
	AddSequential(new DriveForward(0.2, 0.9, true, 90));
	AddSequential(new openGate(true));
	AddSequential(new ParallelToWallWithGyro(16, false));
	AddSequential(new DriveSideways(0.2, 0.25, true));
	AddSequential(new openGate(true));
	AddSequential(new pushGear(true));
	AddSequential(new TurnWheels(0, 0.5));
	AddSequential(new DriveSideways(-0.3, 0.75, false));
	AddSequential(new closeGate(true));
	AddSequential(new closeGate(true));

}



