// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "closeGate.h"
#include "AutoGearSides.h"
#include "DriveForward.h"
#include "TurnToAngle.h"
#include "ParallelToWallWithGyro.h"
#include "openGate.h"
#include "pushGear.h"
#include "DriveSideways.h"
#include "TurnWheels.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoGearSides::AutoGearSides() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	AddSequential(new TurnWheels(0, 0.5));
//#ifndef REAL_ROBOT
//	AddSequential(new DriveForward(Robot::autoPosition ? 0.20 : 0.2, Robot::autoPosition ? 1.75 : 1.5, true, Robot::gearPickup->GetTargetAngle(false)));
//#else
	AddSequential(new DriveForward(0.40, 2.25, true, Robot::gearPickup->GetTargetAngle(false)));
//#endif
	AddSequential(new openGate(true));
	AddSequential(new ParallelToWallWithGyro(16, false));
	AddSequential(new DriveSideways(0.2, 0.25, true));
	AddSequential(new openGate(true));
	AddSequential(new pushGear(true));
	AddSequential(new TurnWheels(0, 0.5));
//#ifndef REAL_ROBOT
	AddSequential(new DriveSideways(-0.3, 0.6, false)); //might need to change
//#endif
	AddSequential(new closeGate(true));
	AddSequential(new closeGate(true));
}



