// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "../OI.h"
#include "../Robot.h"
#include "DumpBalls.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DumpBalls::DumpBalls(bool InAuto): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::dumpster.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_inAuto = InAuto;

}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DumpBalls::Initialize() {
	Robot::dumpster->stopDump();
}

// Called repeatedly when this Command is scheduled to run
void DumpBalls::Execute() {
	if(m_inAuto && !timeoutTriggered)
	{
		SetTimeout(1.0);
		timeoutTriggered = true;
	}
	if(!(Robot::StopCommands && Robot::gearPickup->autoPlaceTriggered && Robot::gearPickup->closeTriggered && Robot::gearPickup->openTriggered
	     && Robot::gearPickup->pushTriggered))
	{
		Robot::dumpster->raiseBox(m_inAuto);
		Robot::dumpster->raiseFlap();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool DumpBalls::IsFinished() {
    return Robot::StopCommands || Robot::gearPickup->autoPlaceTriggered || Robot::gearPickup->closeTriggered || Robot::gearPickup->openTriggered
    	   || Robot::gearPickup->pushTriggered;
}

// Called once after isFinished returns true
void DumpBalls::End() {
	Robot::dumpster->lowerBox();
	Robot::dumpster->releaseFlap();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DumpBalls::Interrupted() {
	Robot::dumpster->lowerBox();
	Robot::dumpster->releaseFlap();
}
