// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "ShoverPosition.h"
#include "MoveToGear.h"
#include "TurnToAngle.h"
#include "openGate.h"
#include "closeGate.h"
#include "pushGear.h"
#include "DriveForward.h"
#include "ParallelToWallWithGyro.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

MoveToGear::MoveToGear() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

	//this is for moving to the gear in teleop
	AddSequential(new ParallelToWallWithGyro(16, true));
	AddSequential(new openGate(true));
	AddSequential(new ParallelToWallWithGyro(8, true));
	AddSequential(new openGate(true));
	AddSequential(new pushGear(true));
	AddSequential(new DriveForward(-0.3, 0.5));
	AddSequential(new closeGate(true));
	AddSequential(new closeGate(true));

 }
