#define LOWER 1
#define RAISE 2
#define NONE  3

// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DUMPSTER_H
#define DUMPSTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Dumpster: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> dumpMotor;
	std::shared_ptr<Servo> dumpServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

public:
	Dumpster();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	void releaseFlap();
	void raiseFlap();
	void raiseBox(bool inAuto = false);
	void lowerBox();
	void stopDump();

	bool reachStopVoltage();

	int dumpState = NONE;
private:
	const int DUMP_PDB_VALUE = 6;
	const double STOP_VOLTAGE = 35.0;

	const double SERVO_END_POS = 0.2;
	const double SERVO_START_POS = 0.7;
	const double DUMP_TELEOP_MOTOR_SPEED = 1.0;
	const double DUMP_AUTO_MOTOR_SPEED = 0.60;
	const double DUMP_DOWN_MOTOR_SPEED = 0.25;
};

#endif
